spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://lucy.c0tm9svq7xyc.ap-northeast-2.rds.amazonaws.com:3306/kinni
    username: pangmin
    password: qorhvkd1514
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    open-in-view: false
  thymeleaf:
    enabled: true
